### ISSUE TITLE
Date formatting flexibility

### ISSUE THREAD

**Issue by vfulco** [fluentdesk/fluentCV#10]
More of an observation vs. criticism but it will be a future impediment. In many professional resume writing circles, the current thinking is to shorten dates down to years only as for longer resumes, specific months and days often do not matter. It also helps the candidate if there were gaps in employment.

Running a test resume through with years only for jobs, education and awards raises the following errors:

$fluentcmd foo_resume.json -o out_foo/resume.doc -t modern

at /home/foo/.nvm/versions/node/v0.12.7/lib/node_modules/fluentcmd/node_modules/fluentlib/src/core/sheet.js:215:27
ERROR: Invalid date format encountered.

Also, for many in between undergrad and grad school, they may want to reflect summer positions simply as "Summer" for start date and "20xx" for end date. TIA.

*** cross-posted this to jsonresume-cli git issues page.

**Comment by devlinjd** [comment]
Thanks for the feedback. This has been discussed over on the JR schema issues page:

- jsonresume/resume-schema#180
- jsonresume/resume-schema#142
- jsonresume/resume-schema#150

IIRC the JR schema now considers these date formats to be valid:

- `YYYY-DD-MM`
- `YYYY-MM`
- `YYYY`
- `""` (empty string, for Present/Current)

FluentCV will support those formats, plus:

- `Mmm YYYY` (Mar 2015)
- `Mmm YY` (Mar 15)
- `Season YY[YY]` (Summer 2009, Summer `11)
- Any date that can be trivially parsed by, e.g, Moment.js or similar

Note that these latter formats, while useful, are technically invalid from the standpoint of a JSON Resume-trained validator. To work around these issues cleanly, we've introduced an extension to the JR format that provides more flexibility in this and some other areas.

**Comment by vfulco** [comment]
Thanks very much.  Not trying to pile on the workload.  Putting thru paces, hope to help when I can.  Not facile with .js whatsoever however.

**Comment by devlinjd** [comment]
You're welcome and the feedback is actually appreciated. Feel free to log issues/suggestions at will (and we're also open to contributions, esp. once the code has stabilized.) Thanks!

**Comment by devlinjd** [comment]
Year-only dates (`YYYY`) should be working in [0.7.2 and later](https://github.com/fluentdesk/fluentCV/releases/latest) along with `YYYY-MM` and `Mmm YYYY` formats. It should also accept `current`, `present`, or `now`. Season dates not implemented yet.

**Comment by gruebait** [comment]
Just a note, you can use `safeStartDate` and `safeEndDate` within any Fluent theme in place of `startDate` and `endDate`. These are Moment.js objects and allow stuff like:

    {{ safeEndDate.format('YYYY') }}
